# Test 2024-04-10 at 04:44:41

name: Test

on:
  push

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SvgSimple
        path: svg

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/MathIntersectionCircleLine
        path: micl

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/GithubCrud
        path: gh

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Install Cairo svg
      run:
        sudo apt install cairosvg

    - name: Cpan
      run:  sudo cpan install -T Data::Dump GDS2 Digest::SHA1

    - name: Test Silicon Wiring
      run:
        perl -Idtt/lib -Isvg/lib -Imicl/lib  lib/Silicon/Chip/Wiring.pm

    - name: Tree
      run:
        tree

    - name: Upload images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl -Idtt/lib -Igh/lib -M"Data::Table::Text" -e"Data::Table::Text::postProcessImagesForDocumentation(log=>1)"

    - uses: actions/upload-artifact@v4
      with:
        name: Wiring
        path: |
          gds
          png
          svg

